module VagrantPlugins
  module Dotvm
    module Config
      class Provision < AbstractConfig
        attr_accessor :type
        attr_accessor :source
        attr_accessor :destination
        attr_accessor :inline
        attr_accessor :path
        attr_accessor :args
        attr_accessor :module_path
        attr_accessor :manifests_path
        attr_accessor :manifest_file
        attr_accessor :privileged
        attr_accessor :run
        attr_accessor :binary_path
        attr_accessor :hiera_config_path
        attr_accessor :environment
        attr_accessor :environment_path
        attr_accessor :binary
        attr_accessor :upload_path
        attr_accessor :keep_color
        attr_accessor :name
        attr_accessor :powershell_args
        attr_accessor :facter
        attr_accessor :options
        attr_accessor :synced_folder_type
        attr_accessor :synced_folder_args
        attr_accessor :temp_dir
        attr_accessor :working_directory
        attr_accessor :client_cert_path
        attr_accessor :client_private_key_path
        attr_accessor :puppet_node
        attr_accessor :puppet_server
        attr_accessor :minion_config
        attr_accessor :run_highstate
        attr_accessor :install_master
        attr_accessor :no_minion
        attr_accessor :install_syndic
        attr_accessor :install_type
        attr_accessor :install_args
        attr_accessor :install_command
        attr_accessor :always_install
        attr_accessor :bootstrap_script
        attr_accessor :bootstrap_options
        attr_accessor :version
        attr_accessor :minion_key
        attr_accessor :minion_id
        attr_accessor :minion_pub
        attr_accessor :grains_config
        attr_accessor :masterless
        attr_accessor :master_config
        attr_accessor :master_key
        attr_accessor :master_pub
        attr_accessor :seed_master
        attr_accessor :run_highstate
        attr_accessor :run_overstate
        attr_accessor :orchestrations
        attr_accessor :colorize
        attr_accessor :log_level
      end
    end
  end
end
