require 'vagrant'
require 'yaml'

require 'vagrant-dotvm/plugin'
require 'vagrant-dotvm/version'
require 'vagrant-dotvm/dotvm'
require 'vagrant-dotvm/configinjecter'

require 'vagrant-dotvm/config/abstractconfig'
require 'vagrant-dotvm/config/root'
require 'vagrant-dotvm/config/machine'
require 'vagrant-dotvm/config/provision'
require 'vagrant-dotvm/config/authorizedkey'
require 'vagrant-dotvm/config/host'
require 'vagrant-dotvm/config/sharedfolder'
require 'vagrant-dotvm/config/option'
require 'vagrant-dotvm/config/route'
require 'vagrant-dotvm/config/network'
