# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-dotvm'

Vagrant.configure(2) do |config|
  config_path = File.dirname(File.expand_path(__FILE__)) + "/config"
  dotvm = VagrantPlugins::Dotvm::Dotvm.new config_path
  dotvm.inject(config)
end
